import classnames from 'classnames';

import { ThemeVariablesInterface } from '../types';
import {
  app,
  black,
  buy,
  caution,
  important,
  information,
  pending,
  primary,
  risk,
  secondary,
  sell,
  shadows,
  status,
  success,
  transparent,
  transparentInverse,
  warning,
} from './colors';

const STAMP = require('../../assets/images/celer_cone_only.svg');
const LOGO = require('../../assets/images/celer_coral_nb.svg');
const CLOSE_ICON = require('../../assets/images/close.svg');
const DISABLED_BG = require('../../assets/images/disabled-background-dark-2.png');
const APP_ICON = require('../../assets/images/login-rm-icon-foreground.png');
const APP_BG = require('../../assets/images/webtrader-tessellation-black-20.svg');
const LOGO_LIGHT = require('../../assets/images/celer_black_nb.svg');

export const themeVariables: ThemeVariablesInterface = {
  AppBg: APP_BG,
  AppIcon: APP_ICON,
  ButtonGroupContained: black[800],
  ButtonGroupContainedSecondary: transparent[300],
  ButtonGroupOutlined: 'transparent',
  ButtonGroupTextBorder: transparentInverse[200],
  Close_icon: CLOSE_ICON,
  Disabled_bg: DISABLED_BG,
  Logo: LOGO,
  Logo_black: LOGO_LIGHT,
  LogoLight: LOGO_LIGHT,
  Stamp: STAMP,
  TextError: important[400],
  app,
  appBar_height: '25px',
  appBg: black[900],
  appPanel_spacing: '4px',
  appVersionContainerBorder: transparentInverse[100],
  appVersionContainerBorderWidth: 0,
  appVersionContainerPadding: '0px',
  appVersionText: transparentInverse[500],
  avatarBg: black.A300,
  avatarText: primary[400],
  bigFigureFontSize: '1.5em',
  bigFigureFontWeight: 600,
  black,
  buy,
  buyButtonBg: 'transparent',
  buyButtonBgHover: buy[400],
  buyButtonBorder: buy[400],
  buyButtonBorderHover: buy[400],
  buyButtonBorderWidth: 1,
  buyButtonText: black[0],
  buyButtonTextHover: black[0],
  caution,
  collapsePanelBg: transparent[300],
  containedPrimaryButtonBg: primary[400],
  containedPrimaryButtonBgHover: primary[400],
  containedPrimaryButtonIcon: black[0],
  containedPrimaryButtonIconHover: black[900],
  containedPrimaryButtonText: black[0],
  containedPrimaryButtonTextHover: black[900],
  containedSecondaryButtonBg: black.A100,
  containedSecondaryButtonBgHover: black.A100,
  containedSecondaryButtonIcon: black[0],
  containedSecondaryButtonIconHover: black[0],
  containedSecondaryButtonText: black[0],
  containedSecondaryButtonTextHover: black[0],
  datePickerBg: 'transparent',
  datePickerBorder: transparentInverse[400],
  datePickerIcon: transparent[900],
  datePickerText: black[50],
  datePopperBodyBg: black[800],
  datePopperBodyBorder: black[800],
  datePopperBodyText: black[700],
  datePopperDateText: black[100],
  datePopperDateTextHoverBg: transparent[300],
  datePopperDateTextHoverText: black[0],
  datePopperHeaderBg: black.A200,
  datePopperHeaderBorder: black[800],
  datePopperHeaderSpinnerArrows: transparentInverse[500],
  datePopperHeaderSpinnerText: black[0],
  datePopperHeaderText: black[400],
  datePopperHighlightedBg: primary[200],
  datePopperHighlightedText: black[900],
  datePopperSelectedBg: primary[200],
  datePopperSelectedText: black[900],
  datePopperTimeBorder: black[900],
  datePopperTimeList: transparent[100],
  datePopperTimeListHover: black[900],
  datePopperTimeListHoverText: black[0],
  datePopperTimeListSelected: primary[200],
  datePopperTimeListSelectedText: black[900],
  datePopperTimeListText: black[0],
  datePopperTodayBg: 'transparent',
  datePopperTodayText: black[0],
  datePopperTriBg: black.A200,
  datePopperTriBorder: black[700],
  defaultButtonBg: 'transparent',
  defaultButtonBgHover: transparentInverse[200],
  defaultButtonBorder: black[500],
  defaultButtonBorderHover: transparentInverse[200],
  defaultButtonBorderWidth: 1,
  defaultButtonIcon: black[0],
  defaultButtonIconHover: black[0],
  defaultButtonText: black[0],
  defaultButtonTextHover: black[0],
  defaultCheckBox: transparentInverse[500],
  defaultCheckBoxChecked: success[500],
  defaultSwitchText: black[300],
  defaultSwitchTextChecked: black[0],
  defaultSwitchThumb: black[600],
  defaultSwitchThumbChecked: black[0],
  defaultSwitchTrack: transparent[900],
  defaultSwitchTrackChecked: black[100],
  defaultTextFieldBg: transparent[300],
  defaultTextFieldBgHover: transparent[200],
  defaultTextFieldBorder: 'transparent',
  defaultTextFieldBorderHover: 'transparent',
  defaultTextFieldBorderRadius: 50,
  defaultTextFieldLabel: transparentInverse[600],
  defaultTextFieldLabelHover: primary[400],
  defaultTextFieldText: black[0],
  defaultTextFieldTextDisabled: transparentInverse[300],
  defaultTextFieldTextHover: black[0],
  dividerDragBg: transparentInverse[500],
  dividerLabel: transparentInverse[500],
  dividerLabelHover: black[0],
  dividerSize: 5,
  drawerWidth: '110px',
  errorCheckBox: important[400],
  errorCheckBoxChecked: important[400],
  expansionSummaryBg: primary[400],
  expansionSummaryBorder: black[800],
  expansionSummaryBorderWidth: 1,
  expansionSummaryText: black[100],
  flagsBorder: black[600],
  flagsBorderRadius: 5,
  flagsBorderWidth: 1,
  fontBase: '12px',
  fontFamily: 'Anaheim, futura-pt, sans-serif;',
  fontL: '1.4rem',
  fontLg: '1.6rem',
  fontRg: '1.1rem',
  fontSm: '1rem',
  fontWeightB: 600,
  fontWeightL: 300,
  fontWeightR: 400,
  fontXL: '2.4rem',
  fontXS: '0.9rem',
  fontXXL: '2.8rem',
  fontXXS: '0.8rem',
  fontXXXL: '3.2rem',
  gridBg: black[800],
  gridBgDark: black.A100,
  gridBgLight: black[0],
  gridBorder: transparent[100],
  gridBorderDark: 'transparent',
  gridBorderLight: transparentInverse[100],
  gridBorderWidget: black[800],
  gridButtonBg: transparentInverse[50],
  gridButtonBgHover: transparentInverse[300],
  gridButtonBorder: 'transparent',
  gridButtonBorderHover: 'transparent',
  gridButtonPrimaryBg: transparentInverse[100],
  gridButtonPrimaryBgHover: primary[200],
  gridButtonPrimaryBorder: 'transparent',
  gridButtonPrimaryTextHover: black.A100,
  gridButtonText: black[0],
  gridButtonTextHover: black[0],
  handleFontSize: '0.7em',
  handleFontWeight: 400,
  important,
  information,
  layoutEdgesBg: black.A100,
  layoutEdgesBorder: transparentInverse[300],
  layoutEdgesBorderWidth: 1,
  layoutEdgestextSelected: primary[400],
  layoutFooterBg: black.A200,
  layoutFooterBorder: transparentInverse[100],
  layoutFooterBorderWidth: 1,
  layoutFooterDescription: transparentInverse[300],
  layoutFooterValue: black[0],
  layoutTabBg: black.A100,
  layoutTabBorder: black.A100,
  layoutTabBorderWidth: 0,
  layoutTabPanelDropIndicator: primary[400],
  layoutTabSetContainerBg: black.A100,
  letterSpacingLg: '0.10rem',
  letterSpacingRg: '0.08rem',
  letterSpacingSm: '0.04rem',
  letterSpacingXL: '0.12rem',
  liteLabelText: transparentInverse[500],
  litePriceLabelText: transparentInverse[500],
  litePriceTitle: black[300],
  lockButtonBg: 'transparent',
  lockButtonBgHover: important[400],
  lockButtonText: black[0],
  lockButtonTextHover: black[0],
  lockContainerBorder: important[400],
  lockContainerBorderWidth: 4,
  lockHeaderText: important[400],
  loginBg: classnames(
    'radial-gradient(circle,',
    black[900],
    '0%,',
    black.A200,
    '70%)'
  ),
  loginBgSize: 'cover',
  loginBodyBottomPadding: '24px 32px 12px 32px',
  loginBodyTopPadding: '24px 32px 12px 32px',
  loginButtonBg: 'transparent',
  loginButtonBgHover: app[400],
  loginButtonBorder: app[400],
  loginButtonBorderHover: app[400],
  loginButtonBorderWidth: 1,
  loginButtonRadius: 20,
  loginButtonText: app[300],
  loginButtonTextHover: black[0],
  loginHeaderAppBgSize: 'auto 120px',
  loginHeaderAppIconBg: null,
  loginHeaderBg: black[900],
  loginHeaderBgImg: null,
  loginHeaderBgSize: 'auto 400%',
  loginHeaderHeight: '13rem',
  loginHeaderLogoImg: LOGO_LIGHT,
  loginHeaderLogoSize: '90%',
  loginPanelBg: black.A100,
  loginPanelBorder: app[400],
  loginPanelBorderWidth: 1,
  loginTextFieldBg: transparent[300],
  loginTextFieldLabel: black[300],
  loginTextFieldRadius: 10,
  loginTextFieldText: black[0],
  midrateBg: black.A200,
  midrateBorder: black[700],
  midrateBorderRadius: 100,
  midrateBorderWidth: 1,
  midrateText: black[0],
  midrateTextDescription: black[0],
  midrateVPosition: 'flex-end',
  modalBg: black.A100,
  modalBorder: black[800],
  modalBorderRadiusModal: 5,
  modalBorderWidth: 1,
  modalHeaderBg: 'transparent',
  modalHeaderBorderBottom: black[900],
  modalHeaderBorderBottomWidth: 0,
  modalHeaderText: black[0],
  modalOverlayBg: transparent[500],
  modalShadow: shadows[2],
  navBg: black.A100,
  navButtonBg: black.A100,
  navButtonBorder: black[900],
  navButtonBorderWidth: 2,
  navButtontext: black[0],
  navButtontextActive: black[0],
  navButtontextHover: black[0],
  navHeight: 30,
  navLogoBg: LOGO,
  navLogoWidth: 75,
  navTitleText: transparentInverse[400],
  newsBg: black.A200,
  newsBorder: black.A100,
  newsBorderWidth: 0,
  newsDescriptionText: transparentInverse[600],
  newsDetailsSource: black.A100,
  newsDetailsTime: black.A100,
  newsHeadlineText: black[0],
  noPriceButtonBg: black[900],
  noPriceButtonBorder: black[800],
  noPriceButtonBorderWidth: 1,
  noPriceButtonText: black[50],
  outlinedPrimaryButtonBgHover: primary[400],
  outlinedPrimaryButtonBorder: primary[400],
  outlinedPrimaryButtonBorderHover: primary[400],
  outlinedPrimaryButtonIcon: black[0],
  outlinedPrimaryButtonIconHover: black[0],
  outlinedPrimaryButtonText: black[0],
  outlinedPrimaryButtonTextHover: black[0],
  outlinedSecondaryButtonBgHover: black[0],
  outlinedSecondaryButtonBorder: black[300],
  outlinedSecondaryButtonBorderHover: black[0],
  outlinedSecondaryButtonIcon: black[0],
  outlinedSecondaryButtonIconHover: black[900],
  outlinedSecondaryButtonText: black[0],
  outlinedSecondaryButtonTextHover: black[900],
  panelHeader_Height: '26px',
  panelHeaderBg: black.A200,
  panelHeaderBorder: transparentInverse[100],
  panelHeaderEditBg: transparentInverse[600],
  panelHeaderShadow: shadows[2],
  panelHeaderTabEditText: transparentInverse[600],
  panelHeaderTabIndicator: primary[400],
  panelHeaderTabIndicatorWidth: 0,
  panelHeaderTabText: transparentInverse[600],
  panelHeaderTabTextHover: transparentInverse[50],
  panelHeaderTabtextSelected: black[0],
  pending,
  pipFontSize: '1em',
  pipFontWeight: 500,
  popoutMenuBg: black[900],
  popoutMenuBorder: black[800],
  popoutMenuBorderWidth: 1,
  popoutMenuItemBg: 'transparent',
  popoutMenuItemBgHover: transparent[100],
  popoutMenuItemBgSelected: transparent[100],
  popoutMenuItemBorder: black.A100,
  popoutMenuItemBorderWidth: 1,
  popoutMenuItemText: black[50],
  popoutMenuItemTextHover: black[50],
  popoutMenuItemtextSelected: primary[400],
  priceButtonDescriptionFontSize: '0.8rem',
  priceButtonDescriptionText: transparentInverse[500],
  priceButtonDescriptionWeight: 300,
  priceButtonFwdFontSize: '1rem',
  priceButtonFwdText: black[50],
  priceButtonFwdWeight: 400,
  priceButtonTitleFontSize: '0.6em',
  priceButtonTitleText: black[0],
  priceButtonTitleWeight: 300,
  primary,
  primaryCheckBox: primary[500],
  primaryCheckBoxChecked: primary[400],
  primarySwitchTextChecked: primary[400],
  primarySwitchThumbChecked: primary[400],
  primarySwitchTrackChecked: primary[400],
  qtyButtonBg: 'transparent',
  qtyButtonBgHover: transparentInverse[100],
  qtyButtonBorder: 'transparent',
  qtyButtonBorderHover: 'transparent',
  qtyButtonBorderRadius: 0,
  qtyButtonBorderWidth: 0,
  qtyButtonText: black[0],
  qtyButtonTextHover: black[0],
  risk,
  rowHeight: '60px',
  searchBarBg: 'transparent',
  searchBarBorder: transparent[300],
  searchBarIcon: black.A100,
  searchBarText: black.A100,
  secondary,
  secondaryCheckBox: black[0],
  secondaryCheckBoxChecked: primary[400],
  secondarySwitchTextChecked: success[600],
  secondarySwitchThumbChecked: success[600],
  secondarySwitchTrackChecked: success[500],
  sell,
  sellButtonBg: 'transparent',
  sellButtonBgHover: sell[400],
  sellButtonBorder: sell[400],
  sellButtonBorderHover: sell[400],
  sellButtonBorderWidth: 1,
  sellButtonText: black[0],
  sellButtonTextHover: black[0],
  settingsExpansionSummaryBg: black.A200,
  settingsExpansionSummaryBorder: transparentInverse[100],
  settingsExpansionSummaryBorderWidth: 1,
  settingsExpansionSummaryText: black[0],
  settingsRowBg: black.A100,
  settingsRowBorder: transparentInverse[100],
  settingsRowBorderWidth: 1,
  settingsRowText: transparentInverse[400],
  shadows,
  spacing_05: '4px',
  spacing_1: '8px',
  spacing_2: '16px',
  spacing_3: '24px',
  spacing_4: '32px',
  spacing_5: '40px',
  spacing_6: '48px',
  spacing_7: '56px',
  spacing_8: '64px',
  spacing_9: '72px',
  spacing_10: '80px',
  spreadBg: black.A200,
  spreadBorder: black[700],
  spreadBorderRadius: 0,
  spreadBorderWidth: 1,
  spreadText: black[0],
  spreadVPosition: 'flex-start',
  status,
  stepBg: black[900],
  stepDisabledBg: transparent[500],
  stepDisabledBorder: transparentInverse[300],
  stepLabelBg: black.A100,
  stepLabelBorder: primary[400],
  stepLabelBorderWidth: 2,
  stepLabelDisabledBg: black.A300,
  stepLabelDisabledBorder: primary[400],
  stepLabelDisabledText: black[300],
  stepLabelFocusBg: black.A100,
  stepLabelFocusBorder: primary[400],
  stepLabelFocusText: black[0],
  stepLabelReadOnlyBg: black[900],
  stepLabelReadOnlyBorder: black[900],
  stepLabelReadOnlyText: black[300],
  stepLabelText: black[300],
  subAppBar_height: '25px',
  subPanelBg: black.A100,
  subPanelBorder: black[800],
  subPanelBorderWidth: 0,
  success,
  tableBg: black.A100,
  tableBorder: 'transparent',
  tableBorderWidth: 1,
  tableCheckBoxBg: primary[500],
  tableCheckBoxIndeterminateBg: primary[500],
  tableCheckBoxSelectedBg: primary[400],
  tableEmptyCellBg: black.A200,
  tableEmptyCellText: black[600],
  tableFilterMenuBg: black.A200,
  tableFilterMenuBorder: black[800],
  tableFilterMenuBorderWidth: 1,
  tableFixedBg: black.A100,
  tableFixedRowBorder: black[800],
  tableFixedRowBorderWidth: 1,
  tableFocusRowBg: transparent[300],
  tableFocusRowText: primary[400],
  tableHeaderBg: 'transparent',
  tableHeaderBorder: black[900],
  tableHeaderBorderWidth: 1,
  tableHeaderDnDGhostBg: black[100],
  tableHeaderDnDGhostText: black.A100,
  tableHeaderMovingBg: black.A200,
  tableHeaderMovingText: black[0],
  tableHeaderShadow: shadows[4],
  tableHeaderText: black[400],
  tableLoadingBg: black.A100,
  tableLoadingBorder: black[800],
  tableLoadingBorderWidth: 1,
  tableLoadingOverlayBg: transparent[300],
  tableLoadingShadow: shadows[4],
  tableLoadingText: black[0],
  tablePrimaryIcon: black[500],
  tableRow_Height: '18px',
  tableRowBg: 'transparent',
  tableRowBorder: black.A100,
  tableRowBorderWidth: 1,
  tableRowEvenBg: transparent[200],
  tableRowText: black[0],
  tableSelectedCellBg: black.A300,
  tableSelectedCellBorder: black[600],
  tableSelectedInputBg: 'transparent',
  tableSelectedInputBorder: 'transparent',
  tableSelectedInputtext: black[0],
  tabsBg: 'transparent',
  tabsBgHover: 'transparent',
  tabsBgSelected: 'transparent',
  tabsBorder: 'transparent',
  tabsBorderHover: black[0],
  tabsBorderSelected: black[0],
  tabsBorderWidth: 0,
  tabsIndicator: primary[400],
  tabsIndicatorWidth: 2,
  tabsScrollBtnText: transparentInverse[300],
  tabsScrollBtnTextHover: transparentInverse[800],
  tabsText: black[700],
  tabsTextHover: black[0],
  tabstextSelected: black[0],
  textDefault: black[50],
  textPrimaryButtonBgHover: transparentInverse[200],
  textPrimaryButtonIcon: primary[400],
  textPrimaryButtonIconHover: primary[400],
  textPrimaryButtonText: primary[400],
  textPrimaryButtonTextHover: primary[400],
  textPrimaryColor: black[0],
  textPrimaryMain: primary[400],
  textSecondaryButtonBgHover: transparentInverse[200],
  textSecondaryButtonIcon: black[300],
  textSecondaryButtonIconHover: black[0],
  textSecondaryButtonText: black[300],
  textSecondaryButtonTextHover: black[0],
  textSecondaryColor: black[500],
  textSecondaryMain: black[300],
  tileHeight: 160 / 4,
  tileWidth: 240,
  transparent,
  transparentInverse,
  userButtonBg: 'transparent',
  userButtonBgHover: 'transparent',
  userButtonBorder: 'transparent',
  userButtonBorderHover: 'transparent',
  userButtonText: black[200],
  userButtonTextHover: black[0],
  warning,
  widgetBg: black.A100,
  widgetBorder: black[800],
  widgetBorderWidth: 1,
  widgetButtonBarBg: black.A200,
  widgetButtonBarBorder: black[800],
  widgetButtonBarBorderWidth: 1,
  widgetFlagsBorder: black[600],
  widgetFlagsBorderRadius: 50,
  widgetFlagsBorderSelected: primary[400],
  widgetFlagsBorderWidth: 2,
  widgetFooterButtonBg: transparentInverse[100],
  widgetFooterButtonBgHover: transparentInverse[300],
  widgetFooterButtonBorder: 'transparent',
  widgetFooterButtonBorderHover: 'transparent',
  widgetFooterButtonBorderWidth: 1,
  widgetFooterButtonText: black[0],
  widgetFooterButtonTextHover: black[0],
  widgetFooterTextFieldBg: transparentInverse[50],
  widgetFooterTextFieldBgHover: transparentInverse[50],
  widgetFooterTextFieldBorder: 'transparent',
  widgetFooterTextFieldBorderHover: 'transparent',
  widgetFooterTextFieldLabel: black[0],
  widgetFooterTextFieldLabelHover: black[0],
  widgetFooterTextFieldText: black[0],
  widgetFooterTextFieldTextHover: black[0],
  widgetHeaderBg: black.A200,
  widgetHeaderBorder: black[800],
  widgetHeaderBorderWidth: 1,
  widgetHeaderShadow: shadows[2],
  widgetHeaderText: black[0],
  widgetHeaderToggleButtonBg: 'transparent',
  widgetHeaderToggleButtonBgHover: transparentInverse[100],
  widgetHeaderToggleButtonBgSelected: 'transparent',
  widgetHeaderToggleButtonBorder: 'transparent',
  widgetHeaderToggleButtonBorderHover: 'transparent',
  widgetHeaderToggleButtonBorderSelected: 'transparent',
  widgetHeaderToggleButtonBorderWidth: 0,
  widgetHeaderToggleButtonText: black[50],
  widgetHeaderToggleButtonTextHover: black[0],
  widgetHeaderToggleButtonTextSelected: primary[400],
  widgetSubHeaderBg: transparent[200],
  widgetSubHeaderBorder: black[800],
  widgetSubHeaderBorderWidth: 1,
  widgetSubHeaderShadow: shadows[2],
  widgetSubHeaderText: transparentInverse[500],
  widgetTextFieldBg: 'transparent',
  widgetTextFieldBgHover: 'transparent',
  widgetTextFieldBorder: 'transparent',
  widgetTextFieldBorderHover: 'transparent',
  widgetTextFieldBorderRadius: 0,
  widgetTextFieldLabel: transparentInverse[600],
  widgetTextFieldLabelHover: primary[400],
  widgetTextFieldText: black[0],
  widgetTextFieldTextDisabled: transparentInverse[600],
  widgetTextFieldTextHover: black[0],
  widgetToggleButtonBg: 'transparent',
  widgetToggleButtonBgHover: transparentInverse[100],
  widgetToggleButtonBgSelected: 'transparent',
  widgetToggleButtonBorder: 'transparent',
  widgetToggleButtonBorderHover: 'transparent',
  widgetToggleButtonBorderRadius: 0,
  widgetToggleButtonBorderSelected: 'transparent',
  widgetToggleButtonBorderWidth: 0,
  widgetToggleButtonText: black[0],
  widgetToggleButtonTextHover: black[0],
  widgetToggleButtonTextSelected: black[0],
  widgetVWAPBorder: primary[400],
  widgetVWAPBorderWidth: 1,
  widgetVWAPText: primary[400],
  widgetVWAPTextDepth: primary[400],
};
